name: Install HomaBelly

on:
  workflow_dispatch:

jobs:
  homabelly-install:
    name: Install HomaBelly with the installer
    runs-on: ubuntu-latest
    steps:
      - name: Install HomaBelly
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          buildMethod: Build.Install
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          allowDirtyBuild: true
          versioning: None

      - name: Upload .unitypackage to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build/*/*/*.unitypackage
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - uses: actions/upload-artifact@v3
        with:
          name: project-after-install
          path: Assets/
